### ISSUE TITLE
PiG: Check for >0 build configs and builds when generating maven repo

### ISSUE THREAD

**Issue by paulgallagher75** [project-ncl/bacon#216]
Noticed by Souvik Ghosh

when running PiG (old version so should have the same result here) with '--skipBuilds  --skipPncUpdate' and the build group is either created already or actually created by this run (I don't know which) the maven repo generator still runs and tries to retrieve the artifacts and dependencies from the latest builds within the build group, however there was no build configs and the error was not very descriptive 

```
Skipping builds
Generating maven repo for build group [Red Hat Integration - DV 8.0 ER4]
repackaging the repository
Exception in thread "main" java.lang.IllegalArgumentException: Parameter 'directory' is not a directory: /tmp/deliverable-generation6403676828147706858/integration-dv-8.0.0.ER4-maven-repository/maven-repository
```

As there was no build configs/builds to retrieve it went onto try and repackage (create the maven repo zip) from a non existent tmp directory, I suggest a check is added to the start of the maven repo generator to give out a better message about there being no build configs/builds in PNC when PiG checks PNC and exit as this would be an error.

**Comment by svkcemk** [comment]
Thanks @paulgallagher75

**Comment by thescouser89** [comment]
@paulgallagher75 Why were there no build configs? Right now the logic is:
1. get build group
2. get build configs in build group
3. find the latest successful build in the build configs

I wonder what are the scenarios that lead to point 2 returning empty.

**Comment by paulgallagher75** [comment]
So its an edge case, the user ran a new pig config with a new build group milestone and build configs etc defined, however forgot to remove '--skipBuilds --skipPncUpdate' from the docker run they had done before, this made pig create the new milestone and build group but no build configs, however it continued to generate a maven repo etc which is very confusing as it should have just checked there was no build configs or builds done and gave a better message than what he saw

**Comment by thescouser89** [comment]
Ack! Thanks for the explanation! I'll see if we can handle it.

**Comment by jbartece** [comment]
Moved to NCL-5980
