### ISSUE TITLE
Option to be strict / tolerant for missing source jars 

### ISSUE THREAD

**Issue by rnc** [project-ncl/bacon#221]
This is when constructing the maven repo zip. From a conversation with @michalszynkiewicz  on cpaas-users.

This would be useful to pick up situations where a build is missing a source jar rather than silently continuing.

**Comment by thescouser89** [comment]
Ah so right now PiG is tolerant but we want to provide a flag for it to be strict?

**Comment by thescouser89** [comment]
Closing. Moved to NCL-5973 :)
