### ISSUE TITLE
pig: validation of build-config.yaml

### ISSUE THREAD

**Issue by michalszynkiewicz** [project-ncl/bacon#246]

**Comment by thescouser89** [comment]
Haa I wanted to add that while working on pig testing and hitting errors due to lack of keys in configs.

**Comment by michalszynkiewicz** [comment]
Sorry for the cryptic title. This is about validating build-config.yaml

**Comment by thescouser89** [comment]
Ahhhhhhhhhh! gotcha :)

**Comment by thescouser89** [comment]
Related to #300

**Comment by jbartece** [comment]
Moved to NCL-5982
