### ISSUE TITLE
Ensure that --releaseStorageUrl is available in the PiG run

### ISSUE THREAD

**Issue by goldmann** [project-ncl/bacon#269]
Standalone PiG exposed the `--releaseStorageUrl` parameter which is currently not available in the new way of invoking PiG. This prameter is used by CPaaS.

**Comment by michalszynkiewicz** [comment]
with the linked PR, it will be possible to either set the URL with `-DreleaseStorageUrl` or do it in the build config yaml

**Comment by goldmann** [comment]
@michalszynkiewicz Can we add it to the `bacon pig run` command as a parameter like it was before?

**Comment by michalszynkiewicz** [comment]
good point, I'll change the system property to a command parameter for `run` and `configure`
