### ISSUE TITLE
introduce an alternative to pig's release.sh

### ISSUE THREAD

**Issue by michalszynkiewicz** [project-ncl/bacon#270]

**Comment by michalszynkiewicz** [comment]
should be done it's not testsed

**Comment by goldmann** [comment]
Do you have a link to commit or PR maybe?

**Comment by goldmann** [comment]
Any usage instructions as well maybe?

**Comment by michalszynkiewicz** [comment]
https://github.com/project-ncl/bacon/pull/280 and https://github.com/project-ncl/bacon/pull/282

```
java -Dpig.continue -jar cli/target/bacon.jar pig release <path to build config dir>
```

**Comment by michalszynkiewicz** [comment]
As I see it  now, it would be good to get rid of `-Dpig.continue` :laughing: 

It needs to have access to the context of previous executions. The context is stored by default in `/tmp/pig-context` (I'll change it to `/tmp/pig-context.json` today)
`-Dpig.context.dir` can be used to change this location, but I'll change it to `pig.context.location` since it's not a directory but a file :)

**Comment by michalszynkiewicz** [comment]
The `release` operation should generate an nvr list and push builds to brew. It should also genrate `upload-to-candidates.sh` script that can be used to trigger RCM scripts to copy stuff from staging to candidates. But IMO CPaaS should not use it and have something on its own.

Having said all that, it's not tested yet. Mostly due to problems I had with brew push (that I should be able to workaround now)

**Comment by goldmann** [comment]
Hrm, access to context may be problematic in case of CPaaS run. By design CPaaS executions are stateless. I need to think about it next week.

**Comment by goldmann** [comment]
I should be able to use workspace to share the context between runs though.

**Comment by goldmann** [comment]
@michalszynkiewicz How would I specify the `pig.continue` flag when using the `bacon` CLI wrapper instead of running it from JAR?
