### ISSUE TITLE
Unable to use a custom configuration path

### ISSUE THREAD

**Issue by goldmann** [project-ncl/bacon#271]
```
$ bacon --configPath=abc pig --help
[ERROR] - Missing argument/option: A value pig was given as an argument, but the command do not support it.
```

**Comment by michalszynkiewicz** [comment]
shouldn't it be `bacon pig --configPath=abc` ?

**Comment by goldmann** [comment]
It could be, but it's a bit counter-intuitive, since this:

```
$ bacon --help
Usage: bacon [<options>]
Bacon CLI

Options:
  -h, --help        print help
  -V, --version     print version
  -v, --verbose     Verbose output
  -p, --configPath  Path to PNC configuration folder
  --profile         PNC Configuration profile

bacon commands:
    pnc  PNC sub-command
    da   Dependency Analysis related commands
    pig  PiG tool
```

..suggest that this is a global parameter.

**Comment by goldmann** [comment]
This becomes an issue where the `pig` and the `bacon` part of the command is prepared in different contexts. I would like to prepare: `bacon --configPath ${tmpDir}` somewhere else and then just add to this other flags constructing:

```
bacon --configPath ${tmpDir} ${otherFlags}
```

**Comment by michalszynkiewicz** [comment]
Maybe specifying the config location with env varialbe would be better for that?

**Comment by goldmann** [comment]
Yep, that would work well in my use case!

**Comment by michalszynkiewicz** [comment]
better validation message should be printed with https://github.com/project-ncl/bacon/pull/273

**Comment by michalszynkiewicz** [comment]
I think `PNC_CONFIG_PATH` should work (https://github.com/project-ncl/bacon/blob/30c91c882939eee4689f33f6018fab5d62101cdd/common/src/main/java/org/jboss/pnc/bacon/common/cli/AbstractCommand.java#L120)

**Comment by michalszynkiewicz** [comment]
@goldmann can we close this?

**Comment by goldmann** [comment]
Yes, works for me!
