### ISSUE TITLE
pig bacon build prints build log to the console

### ISSUE THREAD

**Issue by michalszynkiewicz** [project-ncl/bacon#274]
For a successful build, it makes no sense to download the build log, this thing can be huge.
We should not download the log and print it to the console

**Comment by michalszynkiewicz** [comment]
@thescouser89 WDYT?

**Comment by thescouser89** [comment]
Makes sense!

**Comment by thescouser89** [comment]
@michalszynkiewicz Which command did you run that printed logs? On the PiG side?

**Comment by thescouser89** [comment]
@michalszynkiewicz #308 only prints the logs if the build is unsuccessful. Let me know if you also want the logs to not print for *any* build status: whether successful or not :)
