### ISSUE TITLE
The --jsonOutput switch is not honored when executing PiG commands

### ISSUE THREAD

**Issue by goldmann** [project-ncl/bacon#289]
This is an inconsistent behavior.

**Comment by michalszynkiewicz** [comment]
so sometimes a build is successful and you're getting output as yaml and not json with this switch?

**Comment by goldmann** [comment]
I get plain text output when I run `bacon pig run`, it does not print any JSON. Can you confirm it?

**Comment by goldmann** [comment]
```
bash-5.0$ bacon pig run build-configurations/cpaas/development --jsonOutput
[INFO ] - Generating milestone for versionId ProductVersion(super=ProductVersionRef(id=234, version=1.0, attributes={BREW_TAG_PREFIX=cpaas-tp-1.0-pnc}), product=ProductRef(id=175, name=CPaaS Test Product, description=null, abbreviation=cpaas-tp, productManagers=null, productPagesCode=null), currentProductMilestone=ProductMilestoneRef(id=257, version=1.0.0.ER1, endDate=null, startingDate=2020-08-06T00:00:00Z, plannedEndDate=2020-08-07T00:00:00Z), productMilestones={257=ProductMilestoneRef(id=257, version=1.0.0.ER1, endDate=null, startingDate=2020-08-06T00:00:00Z, plannedEndDate=2020-08-07T00:00:00Z), 269=ProductMilestoneRef(id=269, version=1.0.1.DR1, endDate=null, startingDate=2020-08-12T00:00:00Z, plannedEndDate=2020-08-13T00:00:00Z)}, productReleases={}, groupConfigs={646=GroupConfigurationRef(id=646, name=CPAAS-TP-1.0)}, buildConfigs={2338=BuildConfigurationRef(id=2338, name=dcheung-test-cpaas.tp-cpaas-test-pnc-gradle-1.0.0, description=null, buildScript=gradle clean publish, scmRevision=master, creationTime=2020-08-12T19:44:50.882Z, modificationTime=2020-08-12T19:44:50.866Z, buildType=GRADLE, defaultAlignmentParams=--info -DdependencySource=REST -DrepoRemovalBackup=repositories-backup.xml -DignoreUnresolvableDependencies=true), 2315=BuildConfigurationRef(id=2315, name=cpaas.tp-cpaas-test-pnc-gradle-1.0.0, description=null, buildScript=gradle clean publish, scmRevision=master, creationTime=2020-08-06T08:54:20.323Z, modificationTime=2020-08-10T18:47:41.899Z, buildType=GRADLE, defaultAlignmentParams=--info -DdependencySource=REST -DrepoRemovalBackup=repositories-backup.xml -DignoreUnresolvableDependencies=true), 2336=BuildConfigurationRef(id=2336, name=cpaas.tp-cpaas-test-pnc-maven-1.x, description=null, buildScript=mvn -Dinsecure.repositories=WARN clean deploy, scmRevision=master, creationTime=2020-08-12T12:13:14.946Z, modificationTime=2020-08-12T12:13:25.174Z, buildType=MVN, defaultAlignmentParams=-DdependencySource=REST -DrepoRemovalBackup=repositories-backup.xml -DversionSuffixStrip= -DreportNonAligned=true)}) and milestone 1.0.0.ER1 in PNC
[INFO ] - Adding/updating build configurations
[INFO ] - Performing builds of build group 646 in PNC
[INFO ] - waiting for finish of group build 1922
```

This one is a blocker for us since we cannot get information what we've built. If `jsonOutput` is specified, we should not see logs as-is, but a JSON representation of appropriate object should be returned.

**Comment by goldmann** [comment]
The good part is that everything we see above is stderr, on stdout only a single character is returned, a dot: `.`. I would expect it to return object representation instead.

**Comment by thescouser89** [comment]
Ah that stupid dot. I'll fix that.

**Comment by goldmann** [comment]
@thescouser89 Thanks! What will you return instead?

**Comment by thescouser89** [comment]
The stupid dot was to show progress while it was waiting for the group build to finish. Unfortunately it was print to stdout instead of stderr.

**Comment by thescouser89** [comment]
Yeah it'll print:

```
PiG run completed, the results are in: " + Paths.get(context().getTargetPath()).toAbsolutePath();
```
which when converted to JSON, will still just print a string. (See: https://github.com/project-ncl/bacon/blob/master/pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java#L193)

Given that 'pig run' goes through all the steps, what would be a useful output that CPaaS could consume? Would the results of the successful group build be enough?

**Comment by goldmann** [comment]
I don't know internals of PNC, but when I hear build group I think about multiple builds. If this would be true, I would expect an output that would return general status of the build group + build information run for all executed builds (metadata).

Saying this, if there is the same information (or similar) available in the PiG output directory I could read, I could use it as well.

Generally, I'm looking for build ID's specifically to look up artifacts in case of successful run.

**Comment by thescouser89** [comment]
That makes sense. I'll see what I can do. Thanks for all the feedback!

**Comment by thescouser89** [comment]
Woah sorry that shouldn't have been closed.

**Comment by goldmann** [comment]
We can leave this ticket as a general ticket, the `bacon pig run` specific call should be covered by #313.

**Comment by goldmann** [comment]
This can be worked after the 2.0.0 release.

**Comment by thescouser89** [comment]
Yeah I think it's actually honoured. However we just return a string right now in `pig run` so alll you see from the output will be the string. Will triple-check it once we print useful output in `pig run`. Keeping it open for now :)

**Comment by thescouser89** [comment]
Confirmed that it works ok:

```bash
$ java -jar cli/target/bacon.jar pig run /home/dcheung/projects/work/build-configurations/empty --skipBuilds --skipSharedContent --skipJavadoc --skipSources  --skipRepo --skipBranchCheck --jsonOutput
[lots of logs omitted]
[INFO ] - PiG run completed, the results are in: /home/dcheung/projects/work/bacon/target
{"empty":{"internalScmUrl":"<gerrit>/empty.git","scmRevision":"52d5b89bbcc39e77f09c4a4ca070f75a41b55819","id":"1968","name":"empty","buildLog":null,"builtArtifacts":[{"gapv":"com.github.michalszynkiewicz.test:empty:jar:version","fileName":"empty-version.jar","downloadUrl":"http://indy/versionjar"},{"gapv":"com.github.michalszynkiewicz.test:empty:pom:version","fileName":"empty-version.pom","downloadUrl":"http://indy/version.pom"}],"dependencyArtifacts":null}}
```

I'll close this ticket! If it breaks again, feel free to open a new ticket.

**Comment by thescouser89** [comment]
PR merged. For any further comments on this subject, please report in NCL-5957
