### ISSUE TITLE
Artifact get needs optional RSQL parameter 

### ISSUE THREAD

**Issue by rnc** [project-ncl/bacon#295]
As I understand the equivalent of `/v2/builds/{id}/artifacts/built` is `pnc get artifact get -o`. However we need to pass both ID and RSQL into it.

**Comment by thescouser89** [comment]
Hi! Is this for PNC 2.0? I tried it in bacon and it seems ok:
```
~ ❯ bacon pnc build list-built-artifacts 14111 --profile=stage
---
- id: "351110"
  identifier: "cpaas.tp:cpaas-test-pnc-gradle:jar:1.0.0.redhat-00001"
   ...
```

I suspect however this is for PNC 1.x. Will have a look

**Comment by rnc** [comment]
No this is for PNC 2 and Bacon. I want the PNC 1 equivalent of `/build-records/{id}/built-artifacts` which I think is `/v2/builds/{id}/artifacts/built` but we want the ability to pass RSQL. I thought it was 
```
bacon pnc artifact get
```
But perhaps you could clarify the difference between that and 
```
pnc build list-built-artifacts
```

**Comment by thescouser89** [comment]
Hi!

```
bacon pnc build list-built-artifacts
```

should be what you are looking for.

```
~ ❯ bacon pnc build list-built-artifacts -h                                                ✘ 1
Usage: bacon pnc build list-built-artifacts [<options>] <buildId>
List built artifacts

Options:
  --sort            Sort order (using RSQL)
  --query           Query parameter (using RSQL)
  -o, --jsonOutput  use json for output (default to yaml)
  -h, --help        print help
  -V, --version     print version
  -v, --verbose     Verbose output
  -p, --configPath  Path to PNC configuration folder
  --profile         PNC Configuration profile

Argument:
                  Build ID

Examples:

$ bacon pnc build list-built-artifacts 10000

```

**Comment by rnc** [comment]
What is the difference between the two command please?

**Comment by thescouser89** [comment]
Sorry I forgot to answer your question. The first one will only get a specific artifact by its id.

**Comment by rnc** [comment]
Ah so the `Id of item`  in get is _not_ a build ID but the artifact id? Missed that :-)

**Comment by rnc** [comment]
In which case I guess this could be closed - although I do wonder whether its worth clarifying the `pnc artifact get` as it says
```Usage: bacon pnc artifact get [<options>] <id>
Get artifact

Options:
  -o, --jsonOutput  use json for output (default to yaml)
  -h, --help        print help
  -V, --version     print version
  -v, --verbose     Verbose output
  -p, --configPath  Path to PNC configuration folder
  --profile         PNC Configuration profile

Argument:
                  Id of item
```
Would it be worth saying "Get an artifact by its ID" and "Artifact ID of item" ?

**Comment by thescouser89** [comment]
Thanks for the suggestion! I'll update it and potentially other descriptions for 'get' types.

**Comment by thescouser89** [comment]
The PR #314 should fix the first part of your suggestion.

As for the second suggestion, it's hard for me to add the 'Artifact' in the 'Id of Item' simply because that description is defined in the base abstract 'Get' class that all 'get' commands inherit from.
