### ISSUE TITLE
Debug logs shows port numbers in URLs as null

### ISSUE THREAD

**Issue by goldmann** [project-ncl/bacon#298]
I'm seeing logs similar to:

```
[DEBUG] - Requesting: GET http://orch-stage.DOMAIN:null/pnc-rest/v2/build-configs/2315 Headers: Accept:[application/json].
```

All URLs have the port specified as `null`. Is this a configuration issue or logging issue?

**Comment by thescouser89** [comment]
@rnc I guess that would be correct. Is there any issue about it? Or would you like to see more validations around it?

**Comment by rnc** [comment]
@thescouser89 I'll create an internal issue

**Comment by rnc** [comment]
@thescouser89 Added https://github.com/project-ncl/pnc/pull/3262

**Comment by rnc** [comment]
@goldmann As this is within PNC not Bacon - verified with a custom Bacon build that logged 
```
[DEBUG] - Requesting: GET http://orch-stage.DOMAIN.com/pnc-rest/v2/generic-setting/announcement-banner Headers: Accept:[application/json].
```
do you want to close this now ?

**Comment by jbartece** [comment]
Moved to  NCL-5984
