### ISSUE TITLE
Consider reverting to 8 instead of Java 11

### ISSUE THREAD

**Issue by rnc** [project-ncl/bacon#299]
Currently 8 is default in Fedora 32 (and will be changed to 11 in Fedora 33 - see https://fedoraproject.org/wiki/Releases/33/ChangeSet ).
However I have redhat-internal-cert-install-0.1-20.el7.csb.noarch which gives the correct certificates for the _default_ JDK. This means my separate install of 11 does not have the certificates and cannot talk to the internal services. Can we consider reverting to 11 - unless its absolutely required?

**Comment by thescouser89** [comment]
I honestly use the same rpm and have no issues with using java 11 with bacon. I'll however create a PR to revert it.
