### ISSUE TITLE
KBF version in Bacon

### ISSUE THREAD

**Issue by rnc** [project-ncl/bacon#335]
From @dwalluck 

> Should we be moving to Build Finder 2.0-SNAPSHOT, anyway? This is the only version that supports PNC 2.0. PiG had been using Koji only.
> 
> The latest release, Koji Build Finder 1.5 has PNC 1.4 support, but is that the version we want to be using?
> 
> So the options for PNC support for now are: none, 1.4, or 2.0. And 2.0 requires using Build Finder 2.0-SNAPSHOT as opposed to 1.5.
> 

cc @thescouser89 @jbartece

**Comment by jbartece** [comment]
Moved to NCL-5979
