### ISSUE TITLE
ObjectHelper.print() produces mix of line endings

### ISSUE THREAD

**Issue by dwalluck** [project-ncl/bacon#349]
`ObjectHelper.print()` produces a mix of line endings. A string must contain only a single type of line ending.

I'd prefer just to use `\n` across platforms, but `System.lineSeparator()` is also an option.

`ObjectHelper.print()` behavior may also differ depending upon whether Json or Yaml is used. We need to verify that these behave the same with respect to line endings.

The current behavior with `json = true` appears to be `\n` everywhere except the final newline, which uses `System.lineSeparator()` leading to inconsistent line endings and test failures in `ObjectHelperTest.printJson`.

**Comment by jbartece** [comment]
Moved to  NCL-5986
